type AttendeeType = {
    uuid: string;
    title: string;
    first_name: string;
    last_name: string;
    job_title: string;
    company_name: string;
    email_id: string;
    phone_number: string;
    status: string;
    check_in: number;
    event_name: string;
  };
  
  const mockAttendees: AttendeeType[] = [
    {
      uuid: '1',
      title: 'Mr.',
      first_name: 'John',
      last_name: 'Doe',
      job_title: 'Software Engineer',
      company_name: 'TechCorp',
      email_id: 'john.doe@techcorp.com',
      phone_number: '+1-555-1234',
      status: 'Speaker',
      check_in: 1,
      event_name: 'Tech Conference 2024',
    },
    {
      uuid: '2',
      title: 'Ms.',
      first_name: 'Jane',
      last_name: 'Smith',
      job_title: 'Product Manager',
      company_name: 'InnoTech',
      email_id: 'jane.smith@innotech.com',
      phone_number: '+1-555-5678',
      status: 'Delegate',
      check_in: 1,
      event_name: 'InnoTech Expo 2024',
    },
    {
      uuid: '3',
      title: 'Dr.',
      first_name: 'Alice',
      last_name: 'Johnson',
      job_title: 'Chief Marketing Officer',
      company_name: 'MarketMinds',
      email_id: 'alice.johnson@marketminds.com',
      phone_number: '+1-555-9101',
      status: 'Sponsor',
      check_in: 0,
      event_name: 'Marketing Summit 2024',
    },
    {
      uuid: '4',
      title: 'Mr.',
      first_name: 'Bob',
      last_name: 'Brown',
      job_title: 'Data Scientist',
      company_name: 'DataLabs',
      email_id: 'bob.brown@datalabs.com',
      phone_number: '+1-555-1122',
      status: 'Panelist',
      check_in: 1,
      event_name: 'Data Science Conference 2024',
    },
    {
      uuid: '5',
      title: 'Mrs.',
      first_name: 'Charlie',
      last_name: 'Davis',
      job_title: 'UX Designer',
      company_name: 'CreativeWorks',
      email_id: 'charlie.davis@creativeworks.com',
      phone_number: '+1-555-3344',
      status: 'Moderator',
      check_in: 0,
      event_name: 'UX Design Summit 2024',
    },
    {
      uuid: '6',
      title: 'Mr.',
      first_name: 'David',
      last_name: 'Evans',
      job_title: 'Backend Developer',
      company_name: 'DevCo',
      email_id: 'david.evans@devco.com',
      phone_number: '+1-555-5566',
      status: 'Speaker',
      check_in: 1,
      event_name: 'DevCon 2024',
    },
    {
      uuid: '7',
      title: 'Ms.',
      first_name: 'Eve',
      last_name: 'Garcia',
      job_title: 'Software Architect',
      company_name: 'TechWorks',
      email_id: 'eve.garcia@techworks.com',
      phone_number: '+1-555-7788',
      status: 'Delegate',
      check_in: 0,
      event_name: 'Tech Summit 2024',
    },
    {
      uuid: '8',
      title: 'Mr.',
      first_name: 'Frank',
      last_name: 'Harris',
      job_title: 'Solutions Engineer',
      company_name: 'SolutionsCo',
      email_id: 'frank.harris@solutionsco.com',
      phone_number: '+1-555-9900',
      status: 'Sponsor',
      check_in: 1,
      event_name: 'Engineering Expo 2024',
    },
    {
      uuid: '9',
      title: 'Dr.',
      first_name: 'Grace',
      last_name: 'Lee',
      job_title: 'AI Researcher',
      company_name: 'AI Labs',
      email_id: 'grace.lee@ailabs.com',
      phone_number: '+1-555-1023',
      status: 'Panelist',
      check_in: 1,
      event_name: 'AI Summit 2024',
    },
    {
      uuid: '10',
      title: 'Mr.',
      first_name: 'Henry',
      last_name: 'King',
      job_title: 'Lead Developer',
      company_name: 'Tech Innovators',
      email_id: 'henry.king@techinnovators.com',
      phone_number: '+1-555-4321',
      status: 'Moderator',
      check_in: 0,
      event_name: 'Tech Innovators Forum 2024',
    },
    {
      uuid: '11',
      title: 'Ms.',
      first_name: 'Isabella',
      last_name: 'Martinez',
      job_title: 'Product Designer',
      company_name: 'DesignPro',
      email_id: 'isabella.martinez@designpro.com',
      phone_number: '+1-555-6543',
      status: 'Delegate',
      check_in: 0,
      event_name: 'Product Design Summit 2024',
    },
    {
      uuid: '12',
      title: 'Mr.',
      first_name: 'James',
      last_name: 'Miller',
      job_title: 'DevOps Engineer',
      company_name: 'CloudTech',
      email_id: 'james.miller@cloudtech.com',
      phone_number: '+1-555-8765',
      status: 'Speaker',
      check_in: 1,
      event_name: 'DevOps World 2024',
    },
  ];
  
  export default mockAttendees;
  